-- ============================================================
-- SEED: Essential SAT Vocabulary (200 words)
-- Run AFTER migration-vocabulary.sql
-- ============================================================

INSERT INTO public.vocab_lists (title, description, position) VALUES
  ('Essential SAT 200', 'Two hundred high-frequency SAT words. Master these first.', 1)
ON CONFLICT DO NOTHING;

-- Get the list id we just inserted (or already had)
DO $$
DECLARE
  list_id_var BIGINT;
BEGIN
  SELECT id INTO list_id_var FROM public.vocab_lists WHERE title = 'Essential SAT 200' LIMIT 1;

  -- Only seed if the list is empty
  IF NOT EXISTS (SELECT 1 FROM public.vocab_words WHERE list_id = list_id_var) THEN
    INSERT INTO public.vocab_words (list_id, word, part_of_speech, definition, example) VALUES
    (list_id_var, 'abate', 'verb', 'to lessen in intensity or amount', 'The storm finally abated after midnight.'),
    (list_id_var, 'aberration', 'noun', 'a departure from what is normal or expected', 'Her low test score was an aberration; she usually excels.'),
    (list_id_var, 'abhor', 'verb', 'to regard with disgust and hatred', 'She abhors any form of dishonesty.'),
    (list_id_var, 'abstain', 'verb', 'to choose not to do something', 'He abstained from voting on the proposal.'),
    (list_id_var, 'acclaim', 'noun', 'enthusiastic public praise', 'The novel received critical acclaim.'),
    (list_id_var, 'acumen', 'noun', 'sharpness of judgment, especially in practical matters', 'Her business acumen made the company thrive.'),
    (list_id_var, 'adamant', 'adjective', 'refusing to be persuaded; unyielding', 'He was adamant about leaving early.'),
    (list_id_var, 'admonish', 'verb', 'to warn or reprimand firmly', 'The teacher admonished the students for being late.'),
    (list_id_var, 'adversity', 'noun', 'difficult or unpleasant conditions', 'She faced adversity with quiet strength.'),
    (list_id_var, 'aesthetic', 'adjective', 'concerned with beauty or the appreciation of beauty', 'The building has a striking aesthetic appeal.'),
    (list_id_var, 'affable', 'adjective', 'friendly, good-natured, easy to talk to', 'Their affable host made everyone feel welcome.'),
    (list_id_var, 'aggrandize', 'verb', 'to increase the power or status of', 'The minister sought to aggrandize his role.'),
    (list_id_var, 'alacrity', 'noun', 'brisk and cheerful readiness', 'She accepted the invitation with alacrity.'),
    (list_id_var, 'alleviate', 'verb', 'to make less severe', 'The medicine alleviated her pain.'),
    (list_id_var, 'aloof', 'adjective', 'cool and distant; not friendly', 'He remained aloof during the party.'),
    (list_id_var, 'altruistic', 'adjective', 'showing unselfish concern for others', 'Her altruistic acts inspired the community.'),
    (list_id_var, 'ambiguous', 'adjective', 'open to more than one interpretation', 'His answer was deliberately ambiguous.'),
    (list_id_var, 'ambivalent', 'adjective', 'having mixed feelings about something', 'She felt ambivalent about moving abroad.'),
    (list_id_var, 'ameliorate', 'verb', 'to make a situation better', 'New laws were passed to ameliorate working conditions.'),
    (list_id_var, 'amiable', 'adjective', 'having a pleasant, friendly manner', 'The new neighbour is very amiable.'),
    (list_id_var, 'anachronism', 'noun', 'something out of its proper historical time', 'The clock in the medieval painting is an anachronism.'),
    (list_id_var, 'anomaly', 'noun', 'something that deviates from the standard', 'The result was an anomaly in the data.'),
    (list_id_var, 'antagonize', 'verb', 'to cause to become hostile', 'His comments antagonized the audience.'),
    (list_id_var, 'antipathy', 'noun', 'a deep-seated feeling of dislike', 'She felt antipathy toward the new policy.'),
    (list_id_var, 'apathetic', 'adjective', 'showing no interest or concern', 'Voters were apathetic about the election.'),
    (list_id_var, 'apprehensive', 'adjective', 'anxious or fearful about the future', 'She was apprehensive about the exam.'),
    (list_id_var, 'arbitrary', 'adjective', 'based on random choice rather than reason', 'The decision seemed arbitrary and unfair.'),
    (list_id_var, 'arcane', 'adjective', 'mysterious; understood by few', 'The book explains arcane rituals.'),
    (list_id_var, 'arduous', 'adjective', 'requiring great effort', 'The arduous climb left them exhausted.'),
    (list_id_var, 'articulate', 'adjective', 'expressing oneself clearly and fluently', 'She is an articulate public speaker.'),
    (list_id_var, 'ascetic', 'adjective', 'practising severe self-discipline', 'The monk led an ascetic life.'),
    (list_id_var, 'assiduous', 'adjective', 'showing great care and perseverance', 'His assiduous research paid off.'),
    (list_id_var, 'assuage', 'verb', 'to make less intense; to soothe', 'Her words assuaged his fears.'),
    (list_id_var, 'astute', 'adjective', 'having sharp practical judgment', 'An astute investor, she spotted the opportunity early.'),
    (list_id_var, 'audacious', 'adjective', 'showing willingness to take bold risks', 'His audacious plan surprised everyone.'),
    (list_id_var, 'auspicious', 'adjective', 'suggesting future success', 'The clear weather was an auspicious sign.'),
    (list_id_var, 'austere', 'adjective', 'severe or strict; lacking ornament', 'The room had an austere beauty.'),
    (list_id_var, 'avarice', 'noun', 'extreme greed for wealth', 'His avarice was his downfall.'),
    (list_id_var, 'banal', 'adjective', 'so lacking in originality as to be obvious and boring', 'The film offered only banal observations.'),
    (list_id_var, 'belie', 'verb', 'to fail to give a true impression of', 'Her calm voice belied her nervousness.'),
    (list_id_var, 'belligerent', 'adjective', 'hostile and aggressive', 'He became belligerent when challenged.'),
    (list_id_var, 'benevolent', 'adjective', 'kind and well-meaning', 'A benevolent donor funded the school.'),
    (list_id_var, 'benign', 'adjective', 'gentle and kind; harmless', 'The tumour proved to be benign.'),
    (list_id_var, 'bequeath', 'verb', 'to leave something to someone in a will', 'She bequeathed her art collection to the museum.'),
    (list_id_var, 'bolster', 'verb', 'to support or strengthen', 'New evidence bolstered her argument.'),
    (list_id_var, 'bombastic', 'adjective', 'high-sounding but with little meaning', 'His bombastic speech impressed no one.'),
    (list_id_var, 'brazen', 'adjective', 'bold and without shame', 'The brazen theft happened in broad daylight.'),
    (list_id_var, 'brevity', 'noun', 'shortness of time or expression', 'She values brevity in writing.'),
    (list_id_var, 'cacophony', 'noun', 'a harsh mixture of sounds', 'A cacophony of horns filled the street.'),
    (list_id_var, 'cajole', 'verb', 'to persuade by flattery or coaxing', 'He cajoled her into helping him.'),
    (list_id_var, 'callous', 'adjective', 'showing an insensitive disregard for others', 'His callous remarks upset everyone.'),
    (list_id_var, 'candid', 'adjective', 'truthful and straightforward', 'She gave a candid interview.'),
    (list_id_var, 'capricious', 'adjective', 'given to sudden changes of mood', 'The capricious weather ruined the picnic.'),
    (list_id_var, 'censure', 'verb', 'to express severe disapproval of', 'The senator was censured for misconduct.'),
    (list_id_var, 'circumspect', 'adjective', 'wary and unwilling to take risks', 'She was circumspect about sharing details.'),
    (list_id_var, 'clairvoyant', 'adjective', 'having or showing supernatural foresight', 'Her clairvoyant warning came true.'),
    (list_id_var, 'cogent', 'adjective', 'clear, logical, and convincing', 'She made a cogent argument.'),
    (list_id_var, 'colloquial', 'adjective', 'used in ordinary conversation; informal', 'The essay uses too many colloquial expressions.'),
    (list_id_var, 'commensurate', 'adjective', 'corresponding in size or degree', 'Pay should be commensurate with experience.'),
    (list_id_var, 'compelling', 'adjective', 'evoking interest or admiration in a powerful way', 'A compelling story kept readers hooked.'),
    (list_id_var, 'complacent', 'adjective', 'showing smug self-satisfaction', 'After his win he became complacent.'),
    (list_id_var, 'concise', 'adjective', 'expressing much in few words', 'Her report was concise and clear.'),
    (list_id_var, 'condone', 'verb', 'to accept behaviour considered wrong', 'The teacher will not condone cheating.'),
    (list_id_var, 'conjecture', 'noun', 'an opinion formed without firm evidence', 'His theory was pure conjecture.'),
    (list_id_var, 'consensus', 'noun', 'general agreement', 'They reached a consensus after long debate.'),
    (list_id_var, 'conspicuous', 'adjective', 'standing out so as to be clearly visible', 'He was conspicuous in his red coat.'),
    (list_id_var, 'contrite', 'adjective', 'feeling regret for wrongdoing', 'She gave a contrite apology.'),
    (list_id_var, 'conundrum', 'noun', 'a confusing and difficult problem', 'The mystery presented a real conundrum.'),
    (list_id_var, 'corroborate', 'verb', 'to confirm or give support to a statement', 'Witnesses corroborated her story.'),
    (list_id_var, 'credible', 'adjective', 'able to be believed; convincing', 'Her testimony was credible.'),
    (list_id_var, 'cryptic', 'adjective', 'having a meaning that is hidden or hard to understand', 'He left a cryptic note.'),
    (list_id_var, 'cursory', 'adjective', 'hasty and therefore not thorough', 'She gave the report only a cursory glance.'),
    (list_id_var, 'debilitate', 'verb', 'to make weak', 'The illness debilitated him for weeks.'),
    (list_id_var, 'decorum', 'noun', 'behaviour in keeping with good taste', 'The judge demanded decorum in court.'),
    (list_id_var, 'deference', 'noun', 'humble submission and respect', 'She spoke with deference to her elders.'),
    (list_id_var, 'deleterious', 'adjective', 'causing harm or damage', 'Smoking has a deleterious effect on health.'),
    (list_id_var, 'demagogue', 'noun', 'a leader who appeals to popular prejudice', 'The demagogue stirred up the crowd with lies.'),
    (list_id_var, 'denounce', 'verb', 'to publicly declare to be wrong', 'Critics denounced the new policy.'),
    (list_id_var, 'deride', 'verb', 'to mock or ridicule', 'They derided his old-fashioned ideas.'),
    (list_id_var, 'desolate', 'adjective', 'feeling or showing great unhappiness; deserted', 'The desolate landscape stretched for miles.'),
    (list_id_var, 'despondent', 'adjective', 'in low spirits from loss of hope', 'She grew despondent after the rejection.'),
    (list_id_var, 'deter', 'verb', 'to discourage from doing something', 'Heavy rain did not deter the runners.'),
    (list_id_var, 'didactic', 'adjective', 'intended to teach', 'The book has a didactic tone.'),
    (list_id_var, 'diligent', 'adjective', 'showing care and conscientiousness', 'A diligent student, she rarely misses class.'),
    (list_id_var, 'disdain', 'noun', 'feeling that something is unworthy of respect', 'She viewed the offer with disdain.'),
    (list_id_var, 'disparage', 'verb', 'to regard or speak of as unimportant', 'Do not disparage his efforts.'),
    (list_id_var, 'disparate', 'adjective', 'essentially different in kind', 'The two studies reached disparate conclusions.'),
    (list_id_var, 'dissent', 'noun', 'expression of disagreement', 'There was dissent within the committee.'),
    (list_id_var, 'dogmatic', 'adjective', 'inclined to lay down principles as true', 'His dogmatic views frustrated others.'),
    (list_id_var, 'dubious', 'adjective', 'hesitating or doubting', 'She was dubious about his promises.'),
    (list_id_var, 'eclectic', 'adjective', 'deriving ideas from a broad range of sources', 'Her music tastes are eclectic.'),
    (list_id_var, 'efficacious', 'adjective', 'successful in producing the desired result', 'The treatment proved efficacious.'),
    (list_id_var, 'egregious', 'adjective', 'outstandingly bad', 'The report contained egregious errors.'),
    (list_id_var, 'elated', 'adjective', 'extremely happy', 'She was elated by the news.'),
    (list_id_var, 'eloquent', 'adjective', 'fluent or persuasive in speaking or writing', 'An eloquent defender of human rights.'),
    (list_id_var, 'elucidate', 'verb', 'to make clear; explain', 'The professor elucidated the difficult concept.'),
    (list_id_var, 'emulate', 'verb', 'to imitate with the goal of equalling or surpassing', 'Young athletes emulate their heroes.'),
    (list_id_var, 'enervate', 'verb', 'to drain of energy', 'The heat enervated everyone.'),
    (list_id_var, 'enigmatic', 'adjective', 'difficult to interpret or understand', 'Her enigmatic smile puzzled him.'),
    (list_id_var, 'ephemeral', 'adjective', 'lasting for a very short time', 'Fame can be ephemeral.'),
    (list_id_var, 'equanimity', 'noun', 'calmness, especially in a difficult situation', 'She faced the crisis with equanimity.'),
    (list_id_var, 'erudite', 'adjective', 'having or showing great knowledge', 'An erudite lecturer, she explained it perfectly.'),
    (list_id_var, 'esoteric', 'adjective', 'understood by only a small number of people', 'The lecture was too esoteric for most.'),
    (list_id_var, 'eulogy', 'noun', 'a speech in praise, often at a funeral', 'He delivered a moving eulogy.'),
    (list_id_var, 'euphemism', 'noun', 'a mild word substituted for a blunt one', 'Passed away is a euphemism for died.'),
    (list_id_var, 'evanescent', 'adjective', 'soon passing out of sight or memory', 'The evanescent glow of dawn.'),
    (list_id_var, 'exacerbate', 'verb', 'to make a problem worse', 'Stress can exacerbate the condition.'),
    (list_id_var, 'exemplary', 'adjective', 'serving as a desirable model', 'Her behaviour was exemplary.'),
    (list_id_var, 'exonerate', 'verb', 'to absolve from blame', 'New evidence exonerated him.'),
    (list_id_var, 'expedient', 'adjective', 'convenient and practical, sometimes at moral cost', 'It would be expedient to ignore the rule.'),
    (list_id_var, 'expound', 'verb', 'to present and explain in detail', 'She expounded her theory at length.'),
    (list_id_var, 'extol', 'verb', 'to praise enthusiastically', 'Critics extolled the novel.'),
    (list_id_var, 'fastidious', 'adjective', 'very attentive to detail', 'A fastidious editor, she catches everything.'),
    (list_id_var, 'feasible', 'adjective', 'possible to do easily', 'The plan was not feasible on that budget.'),
    (list_id_var, 'fervent', 'adjective', 'having intense feeling', 'A fervent supporter of the cause.'),
    (list_id_var, 'flagrant', 'adjective', 'conspicuously bad', 'A flagrant violation of the rules.'),
    (list_id_var, 'flippant', 'adjective', 'not showing serious or respectful attitude', 'His flippant reply annoyed the judge.'),
    (list_id_var, 'fortuitous', 'adjective', 'happening by chance, especially in a fortunate way', 'Their meeting was entirely fortuitous.'),
    (list_id_var, 'frugal', 'adjective', 'sparing or economical with money', 'A frugal lifestyle helped her save.'),
    (list_id_var, 'futile', 'adjective', 'incapable of producing useful results', 'Their efforts proved futile.'),
    (list_id_var, 'garrulous', 'adjective', 'excessively talkative', 'A garrulous neighbour kept them at the door.'),
    (list_id_var, 'gregarious', 'adjective', 'fond of company; sociable', 'A gregarious leader, she made friends easily.'),
    (list_id_var, 'guile', 'noun', 'sly or cunning intelligence', 'He survived by his guile.'),
    (list_id_var, 'hackneyed', 'adjective', 'overused and unoriginal', 'The plot was hackneyed and predictable.'),
    (list_id_var, 'harbinger', 'noun', 'something that signals what is to come', 'Robins are harbingers of spring.'),
    (list_id_var, 'haughty', 'adjective', 'arrogantly superior', 'Her haughty manner alienated people.'),
    (list_id_var, 'hedonist', 'noun', 'a person devoted to pleasure', 'He lived as a hedonist in his youth.'),
    (list_id_var, 'heretic', 'noun', 'one who holds an opinion contrary to orthodoxy', 'She was branded a heretic.'),
    (list_id_var, 'iconoclast', 'noun', 'one who attacks cherished beliefs', 'An iconoclast, she challenged every convention.'),
    (list_id_var, 'idiosyncrasy', 'noun', 'a characteristic peculiar to an individual', 'His idiosyncrasies made him memorable.'),
    (list_id_var, 'idyllic', 'adjective', 'extremely happy, peaceful, or picturesque', 'An idyllic country setting.'),
    (list_id_var, 'immutable', 'adjective', 'unchanging over time', 'The laws of physics are immutable.'),
    (list_id_var, 'impeccable', 'adjective', 'in accordance with the highest standards', 'Her work is impeccable.'),
    (list_id_var, 'impede', 'verb', 'to delay or prevent', 'Snow impeded the rescue effort.'),
    (list_id_var, 'imperious', 'adjective', 'assuming power without justification', 'His imperious tone offended the staff.'),
    (list_id_var, 'impetuous', 'adjective', 'acting quickly without thought', 'An impetuous decision he later regretted.'),
    (list_id_var, 'implicit', 'adjective', 'suggested though not directly expressed', 'There was an implicit threat in his words.'),
    (list_id_var, 'inadvertent', 'adjective', 'not resulting from deliberate planning', 'An inadvertent error in the data.'),
    (list_id_var, 'incessant', 'adjective', 'continuing without pause', 'The incessant rain ruined the trip.'),
    (list_id_var, 'incipient', 'adjective', 'in an early stage', 'An incipient rebellion was quickly crushed.'),
    (list_id_var, 'incongruous', 'adjective', 'not in harmony with what is around', 'The modern statue looked incongruous in the old square.'),
    (list_id_var, 'indignant', 'adjective', 'feeling anger over unfair treatment', 'She was indignant at the suggestion.'),
    (list_id_var, 'ineffable', 'adjective', 'too great or extreme to be expressed', 'An ineffable joy filled her.'),
    (list_id_var, 'inert', 'adjective', 'lacking the ability to move or act', 'The patient lay inert.'),
    (list_id_var, 'ingenuous', 'adjective', 'innocent and unsuspecting', 'Her ingenuous trust was touching.'),
    (list_id_var, 'inherent', 'adjective', 'existing as a permanent quality', 'There are inherent risks in the job.'),
    (list_id_var, 'innocuous', 'adjective', 'not harmful or offensive', 'The remark seemed innocuous.'),
    (list_id_var, 'insidious', 'adjective', 'proceeding in a subtle but harmful way', 'An insidious disease.'),
    (list_id_var, 'intransigent', 'adjective', 'unwilling to change views', 'The intransigent leader refused to negotiate.'),
    (list_id_var, 'intrepid', 'adjective', 'fearless; adventurous', 'The intrepid explorer crossed the desert.'),
    (list_id_var, 'inveterate', 'adjective', 'having a long-standing habit', 'An inveterate reader.'),
    (list_id_var, 'irascible', 'adjective', 'easily angered', 'The irascible manager shouted often.'),
    (list_id_var, 'judicious', 'adjective', 'showing good judgement', 'A judicious use of resources.'),
    (list_id_var, 'jubilant', 'adjective', 'feeling great happiness and triumph', 'The team was jubilant after the win.'),
    (list_id_var, 'juxtapose', 'verb', 'to place close together for contrast', 'The artist juxtaposed light and shadow.'),
    (list_id_var, 'laconic', 'adjective', 'using very few words', 'His laconic reply ended the discussion.'),
    (list_id_var, 'lament', 'verb', 'to express grief or regret about', 'She lamented her wasted years.'),
    (list_id_var, 'laud', 'verb', 'to praise highly', 'Critics lauded the performance.'),
    (list_id_var, 'lethargy', 'noun', 'a lack of energy and enthusiasm', 'Summer heat induced a lethargy.'),
    (list_id_var, 'loquacious', 'adjective', 'tending to talk a great deal', 'A loquacious host kept the room lively.'),
    (list_id_var, 'lucid', 'adjective', 'expressed clearly; easy to understand', 'A lucid explanation of the theory.'),
    (list_id_var, 'malevolent', 'adjective', 'wishing evil to others', 'A malevolent glare.'),
    (list_id_var, 'malign', 'verb', 'to speak ill of', 'She felt maligned by the rumours.'),
    (list_id_var, 'meticulous', 'adjective', 'showing great attention to detail', 'A meticulous record-keeper.'),
    (list_id_var, 'mitigate', 'verb', 'to make less severe', 'Steps were taken to mitigate the damage.'),
    (list_id_var, 'mundane', 'adjective', 'lacking interest or excitement', 'The job involved mundane tasks.'),
    (list_id_var, 'myriad', 'noun', 'a countless or very great number', 'A myriad of stars.'),
    (list_id_var, 'nefarious', 'adjective', 'wicked or criminal', 'A nefarious plot was uncovered.'),
    (list_id_var, 'nonchalant', 'adjective', 'feeling or appearing casually calm', 'He gave a nonchalant shrug.'),
    (list_id_var, 'novel', 'adjective', 'new or unusual in an interesting way', 'A novel approach to the problem.'),
    (list_id_var, 'noxious', 'adjective', 'harmful, poisonous, or very unpleasant', 'Noxious fumes filled the air.'),
    (list_id_var, 'obfuscate', 'verb', 'to make obscure or unclear', 'Jargon obfuscated her meaning.'),
    (list_id_var, 'obsequious', 'adjective', 'obedient to an excessive degree', 'An obsequious assistant who never disagreed.'),
    (list_id_var, 'obstinate', 'adjective', 'stubbornly refusing to change opinion', 'An obstinate child who refused to eat.'),
    (list_id_var, 'ominous', 'adjective', 'suggesting that bad things are about to happen', 'An ominous silence settled in.'),
    (list_id_var, 'opaque', 'adjective', 'not transparent; hard to understand', 'The legal language was opaque.'),
    (list_id_var, 'opulent', 'adjective', 'rich and luxurious', 'The opulent palace dazzled the visitors.'),
    (list_id_var, 'ostentatious', 'adjective', 'characterised by vulgar display', 'An ostentatious display of wealth.'),
    (list_id_var, 'paradox', 'noun', 'a self-contradictory statement that may be true', 'The paradox puzzled scholars for years.'),
    (list_id_var, 'pedantic', 'adjective', 'excessively concerned with minor details', 'A pedantic insistence on grammar.'),
    (list_id_var, 'pejorative', 'adjective', 'expressing contempt or disapproval', 'A pejorative term for the practice.'),
    (list_id_var, 'penchant', 'noun', 'a strong liking for something', 'A penchant for old films.'),
    (list_id_var, 'perfunctory', 'adjective', 'carried out with minimum effort', 'A perfunctory inspection missed the flaw.'),
    (list_id_var, 'pernicious', 'adjective', 'having a harmful effect, especially gradually', 'The pernicious effects of the drug.'),
    (list_id_var, 'pervasive', 'adjective', 'spreading widely throughout', 'A pervasive feeling of unease.'),
    (list_id_var, 'philanthropy', 'noun', 'the desire to promote welfare of others', 'Her philanthropy funded the new wing.'),
    (list_id_var, 'placate', 'verb', 'to make less angry or hostile', 'He placated his critics with concessions.'),
    (list_id_var, 'plausible', 'adjective', 'seeming reasonable or probable', 'A plausible explanation.'),
    (list_id_var, 'pragmatic', 'adjective', 'dealing with things sensibly and realistically', 'A pragmatic approach to the problem.'),
    (list_id_var, 'precarious', 'adjective', 'uncertain; dependent on chance', 'A precarious balance on the cliff edge.'),
    (list_id_var, 'precocious', 'adjective', 'having developed certain abilities at an earlier age than usual', 'A precocious reader at four.'),
    (list_id_var, 'predilection', 'noun', 'a preference or special liking', 'A predilection for spicy food.'),
    (list_id_var, 'prevalent', 'adjective', 'widespread in a particular area or time', 'Misinformation is prevalent online.'),
    (list_id_var, 'proficient', 'adjective', 'competent or skilled', 'She is proficient in three languages.'),
    (list_id_var, 'profound', 'adjective', 'very great or intense; showing deep insight', 'A profound silence; profound wisdom.'),
    (list_id_var, 'prolific', 'adjective', 'producing much fruit or many works', 'A prolific writer of short stories.'),
    (list_id_var, 'propensity', 'noun', 'an inclination or natural tendency', 'A propensity for daydreaming.'),
    (list_id_var, 'prosaic', 'adjective', 'commonplace; unromantic', 'A prosaic description of the trip.'),
    (list_id_var, 'pugnacious', 'adjective', 'eager to fight or argue', 'His pugnacious manner alienated allies.'),
    (list_id_var, 'quell', 'verb', 'to put an end to', 'Police quelled the disturbance.'),
    (list_id_var, 'querulous', 'adjective', 'complaining in a whining manner', 'A querulous old man.'),
    (list_id_var, 'quintessential', 'adjective', 'representing the perfect example of something', 'The quintessential romantic film.'),
    (list_id_var, 'rancor', 'noun', 'bitterness or resentfulness', 'She felt no rancor toward him.'),
    (list_id_var, 'recalcitrant', 'adjective', 'having an obstinately uncooperative attitude', 'The recalcitrant student refused to comply.'),
    (list_id_var, 'reconcile', 'verb', 'to restore friendly relations between', 'They reconciled after years apart.'),
    (list_id_var, 'redundant', 'adjective', 'not or no longer needed; superfluous', 'Cut redundant words from your essay.'),
    (list_id_var, 'refute', 'verb', 'to prove a statement to be wrong', 'New data refuted the theory.'),
    (list_id_var, 'relegate', 'verb', 'to assign to a lower position', 'The team was relegated to a lower division.'),
    (list_id_var, 'reproach', 'verb', 'to express disapproval to', 'She reproached him for his rudeness.'),
    (list_id_var, 'reticent', 'adjective', 'not revealing thoughts or feelings', 'He was reticent about his past.'),
    (list_id_var, 'reverence', 'noun', 'deep respect for someone or something', 'She spoke of him with reverence.'),
    (list_id_var, 'rhetoric', 'noun', 'the art of effective speaking or writing', 'Political rhetoric filled the speech.'),
    (list_id_var, 'sagacious', 'adjective', 'having keen mental discernment', 'A sagacious adviser.'),
    (list_id_var, 'sanguine', 'adjective', 'optimistic in a difficult situation', 'She remained sanguine despite setbacks.'),
    (list_id_var, 'scathing', 'adjective', 'witheringly scornful', 'A scathing review of the play.'),
    (list_id_var, 'scrupulous', 'adjective', 'careful and thorough; with attention to ethics', 'Scrupulous attention to detail.'),
    (list_id_var, 'sedulous', 'adjective', 'showing dedication and diligence', 'A sedulous student.'),
    (list_id_var, 'serendipity', 'noun', 'finding something good without seeking it', 'The discovery was pure serendipity.'),
    (list_id_var, 'sporadic', 'adjective', 'occurring at irregular intervals', 'Sporadic showers throughout the day.'),
    (list_id_var, 'stoic', 'adjective', 'enduring hardship without showing feelings', 'A stoic acceptance of pain.'),
    (list_id_var, 'subtle', 'adjective', 'delicately complex; not obvious', 'A subtle difference between the two.'),
    (list_id_var, 'superfluous', 'adjective', 'unnecessary, especially through being more than enough', 'Cut all superfluous detail.'),
    (list_id_var, 'tacit', 'adjective', 'understood without being said', 'A tacit agreement between them.'),
    (list_id_var, 'tenacious', 'adjective', 'holding firmly; persistent', 'A tenacious investigator.'),
    (list_id_var, 'terse', 'adjective', 'sparing in the use of words; abrupt', 'A terse reply.'),
    (list_id_var, 'transient', 'adjective', 'lasting only for a short time', 'Transient guests at the hotel.'),
    (list_id_var, 'trepidation', 'noun', 'a feeling of fear about something that may happen', 'She approached the stage with trepidation.'),
    (list_id_var, 'ubiquitous', 'adjective', 'present, appearing, or found everywhere', 'Mobile phones are ubiquitous.'),
    (list_id_var, 'undermine', 'verb', 'to weaken gradually', 'His remarks undermined her authority.'),
    (list_id_var, 'unprecedented', 'adjective', 'never done or known before', 'Unprecedented levels of rainfall.'),
    (list_id_var, 'vacillate', 'verb', 'to alternate between opinions', 'She vacillated between the two options.'),
    (list_id_var, 'venerate', 'verb', 'to regard with great respect', 'They venerated their teacher.'),
    (list_id_var, 'verbose', 'adjective', 'using more words than needed', 'A verbose explanation lost the reader.'),
    (list_id_var, 'vex', 'verb', 'to annoy or frustrate', 'The puzzle vexed him for hours.'),
    (list_id_var, 'vindicate', 'verb', 'to clear of blame or suspicion', 'Evidence vindicated her decision.'),
    (list_id_var, 'volatile', 'adjective', 'liable to change rapidly and unpredictably', 'A volatile situation in the market.'),
    (list_id_var, 'wary', 'adjective', 'feeling or showing caution about danger', 'Wary of strangers.'),
    (list_id_var, 'whimsical', 'adjective', 'playfully quaint or fanciful', 'A whimsical drawing of dancing animals.'),
    (list_id_var, 'zealous', 'adjective', 'having great energy in pursuit of a cause', 'A zealous defender of the environment.');
  END IF;
END $$;
